### ISSUE TITLE
Error: pygame.image.load() doesn't exist

### ISSUE THREAD

**Issue by jrslagle** [Master-Foo/game#69]
Both Tom and I are having this issue. The game won't run. If we figure it out, I'll post the fix.

```
  File "/home/jrslagle/Code/TerraCraft/game/source/library/action/animation.py", line 43, in load_frame
    fra = pygame.image.load(tmp_frame).convert_alpha()
pygame.error: Couldn't open resources/images/rock/animations/stand/north/000.png
```

What I've figured out so far:
that line: `fra = pygame.image.load(tmp_frame).convert_alpha()` was exactly the same on working versions, so it's not a change we did.

pygame.image.load() should be located in 
/home/jrslagle/.PyCharmCE2016.3/system/python_stubs/-1247972723/pygame/imageext.py
but that method doesn't exist there. It's like the library changed.

**Comment by techwulf** [comment]
Alright issue #69 ha ha.

**Comment by Master-Foo** [comment]
I haven't gone down the rabbit hole to figure this out, however, here is my suspicion...

`pygame.error: Couldn't open resources/images/rock/animations/stand/north/000.png`

most likely means pygame's `load()` is trying to find that file, but when it looks in that location, it doesn't exist.

The recent code restructure I did last weekend could have been the culprit because I moved the executables into the `/demo/ directory. Since the resource files are relative to the path where the executable is run, if you run the executables from **inside** the `/demo` directory, it will fail.

Always run the executables from the root directory of the project.

`/path/to/game/$ ./demo/demo.py`

This will fail:

`/path/to/game/demo/$ ./demo.py`

alternatively, there is a shortcut to demo in the root directory of the project:

`./run`

I don't know if that will solve the problem, but without being able to replicate what is happening, this is my best guess.

**Comment by Master-Foo** [comment]
OK, I just did a sanity check to confirm my suspicions by running `./demo.py` **inside** the demo directory. Here is the results.

```bash
Traceback (most recent call last):
  File "./demo.py", line 10, in <module>
    game = game.Game()
  File "/home/masterfoo/git/game/source/systems/game/game.py", line 7, in __init__
    self.universe = universe.Universe()
  File "/home/masterfoo/git/game/source/systems/location/universe/universe.py", line 8, in __init__
    model.Model.__init__(self, parent)
  File "/home/masterfoo/git/game/source/systems/location/universe/model/model.py", line 9, in __init__
    self.galaxy = galaxy.Galaxy(self)
  File "/home/masterfoo/git/game/source/systems/location/galaxy/galaxy.py", line 8, in __init__
    model.Model.__init__(self, parent)
  File "/home/masterfoo/git/game/source/systems/location/galaxy/model/model.py", line 9, in __init__
    self.solar_system = solar_system.SolarSystem(self)
  File "/home/masterfoo/git/game/source/systems/location/solar_system/solar_system.py", line 8, in __init__
    model.Model.__init__(self, parent)
  File "/home/masterfoo/git/game/source/systems/location/solar_system/model/model.py", line 9, in __init__
    self.planet = planet.Planet(self)
  File "/home/masterfoo/git/game/source/systems/location/planet/planet.py", line 8, in __init__
    model.Model.__init__(self, parent)
  File "/home/masterfoo/git/game/source/systems/location/planet/model/model.py", line 22, in __init__
    self.homestead = homestead.Homestead()
  File "/home/masterfoo/git/game/source/systems/location/homestead/homestead.py", line 8, in __init__
    model.Model.__init__(self, parent)
  File "/home/masterfoo/git/game/source/systems/location/homestead/model/model.py", line 27, in __init__
    rock0 = rock.Rock(self, 0.95, bauxite.Bauxite().composition)
  File "/home/masterfoo/git/game/source/concrete/entities/inanimate/rock/rock.py", line 9, in __init__
    view.View.__init__(self)
  File "/home/masterfoo/git/game/source/concrete/entities/inanimate/rock/view/view.py", line 11, in __init__
    self.animation = action.Action(stand.stand_data)
  File "/home/masterfoo/git/game/source/library/action/action.py", line 15, in __init__
    self.assign_directions(data)
  File "/home/masterfoo/git/game/source/library/action/action.py", line 21, in assign_directions
    self.north = animation.Animation(data, ani)
  File "/home/masterfoo/git/game/source/library/action/animation.py", line 18, in __init__
    self.load_frames(animation["frames"])
  File "/home/masterfoo/git/game/source/library/action/animation.py", line 28, in load_frames
    self.load_frame(f)
  File "/home/masterfoo/git/game/source/library/action/animation.py", line 43, in load_frame
    fra = pygame.image.load(tmp_frame).convert_alpha()
pygame.error: Couldn't open resources/images/rock/animations/stand/north/000.png
```

So, I'm pretty confident that you guys are **not** executing from the root directory.

BTW: I already explained this in detail in: **Major Code Cleanup #66** which everyone should have read already because I assigned it to everyone and stated it's importance that it be fully grokked. You know... because of things like this.

**Comment by jrslagle** [comment]
Yep, that was the problem. Tom also navigates right to the file before executing.

And I did read that entire explanation of project structure.
